name: Linux/Compile, Build, Run, and Test

on:
  push:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Prepare
        run: git submodule update --recursive
      - name: Install
        run: make install
        shell: bash
      - name: Build
        run: make clean build build_test
        shell: bash
      - name: Test
        run: make run_tests
        shell: bash