name: Benchmark with Node.JS and Python
on:
  push:
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Prepare
        run: git submodule update --recursive
      - name: Install
        run: make install
        shell: bash
      - name: Benchmark
        run: make -B benchmark
        shell: bash
      - name: Outcome
        run: |
          echo "Test 1";
          cat benchmark/tmp/test1.result;
          echo "Test 2";
          cat benchmark/tmp/test2.result;
        shell: bash