name: Build & Test
on:
  push:
  pull_request:
    types: [opened]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest MinGW",
            os: windows-latest,
            cxx: "g++",
          }
          - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest,
            cxx: "g++-11"
          }
          - {
            name: "macOS Latest GCC",
            os: macos-latest,
            cxx: "g++"
          }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Install dependencies on windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install mingw --version 11.2.0.07112021 --force
          make --version
          gcc --version
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.config.name, 'Ubuntu Latest GCC')
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11 make
          make --version
          gcc-11 --version
          g++-11 --version
      - name: Install dependencies on macos
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install p7zip make gcc
          make --version
          gcc --version
          g++ --version
      - name: Configure
        shell: bash
        run: |
          make -B install
      - name: Build
        shell: bash
        run: |
          make -B clean build build_tests COMPILER_CPP=${{ matrix.config.cxx }}
      - name: Test
        shell: bash
        timeout-minutes: 10
        run: |
          make -B run_tests
          cp bin/log/performance* benchmark/integration_tests/
      - name: Commit test score
        if: ${{ github.ref == 'refs/heads/master' && startsWith(matrix.config.name, 'Ubuntu Latest GCC') }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "${{ github.sha }} ${{ matrix.config.os }}" >> benchmark/integration_tests/commit_hash
          git add .
          git commit -m "Add pipeline testing score" -a
      - name: Push static code analysis
        if: ${{ github.ref == 'refs/heads/master' && startsWith(matrix.config.name, 'Ubuntu Latest GCC') }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' && startsWith(matrix.config.name, 'Ubuntu Latest GCC') }}
        uses: qoomon/deploy-to-github-pages-action@v1
        with:
          GITHUB_PAGES_SOURCE_DIR: ./bin/log
          GITHUB_PAGES_BRANCH: gh-pages
          GITHUB_PAGES_REPLACE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}