name: Build under Windows and Ubuntu Linux

on: [push]

jobs:
  build-on-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: jinja
      run: cd ./lib/Jinja2Cpp/ && rm -rf .jinja2cpp-{build,install}/* && cd .jinja2cpp-build && cmake ../ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../.jinja2cpp-install -DJINJA2CPP_BUILD_TESTS=OFF -DJINJA2CPP_DEPS_MODE=internal -DJINJA2CPP_CXX_STANDARD=17 && cmake --build . --config Release --target install
      shell: bash
    - name: root dir
      run: cd ../../../
      shell: bash
    - name: make build
      run: make build
      shell: bash
    - name: make build_test
      run: make build_test
      shell: bash
    - name: make run_tests
      run: make run_tests
      shell: bash

  build-on-linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: jinja
      run: cd ./lib/Jinja2Cpp/ && rm -rf .jinja2cpp-{build,install}/* && cd .jinja2cpp-build && cmake ../ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../.jinja2cpp-install -DJINJA2CPP_BUILD_TESTS=OFF -DJINJA2CPP_DEPS_MODE=internal -DJINJA2CPP_CXX_STANDARD=17 && cmake --build . --config Release --target install
      shell: bash
    - name: root dir
      run: cd ../../../
      shell: bash
    - name: make build
      run: make build
      shell: bash
    - name: make build_test
      run: make build_test
      shell: bash
    - name: non-make run-tests
      run: mkdir -p ./bin/log && ./bin/test.exe
      shell: bash
    - name: make run_tests
      run: make run_tests
      shell: bash