name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make build
      run: GCC=g++ make build
    - name: make build_test
      run: GCC=g++ make build_test
    - name: make run_tests
      run: GCC=g++ make run_tests
