name: Code quality control
on: 
  push:
  pull_request:
    types: [opened]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check_library: disable
          skip_preprocessor: disable
          enable: all
          exclude_check: ./lib
          inconclusive: enable
          inline_suppression: disable
          force_language: auto-detect
          force: disable
          max_ctu_depth: 4
          platform: unspecified
          std: c++17
          output_file: ./cppcheck_report.txt
          other_options: disable

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }} # your branch name goes here
