name: Code quality control

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build & Test, build, Ubuntu Latest GCC]
    types: [completed]
    branches:
      - '**'

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install CppCheck
      run: |
        sudo -H apt-get update -y
        sudo -H apt-get install cppcheck
    - name: Run Cppcheck
      run: cppcheck --std=c++20  -I./tests -I./src --error-exitcode=1 --xml --xml-version=2 --force --enable=all src 2>cppcheck_res.xml
    - name: Generate Report
      if: ${{ failure() }}
      run: cppcheck-htmlreport --title=WebFrame --file=cppcheck_res.xml --report-dir=report
    - name: Upload Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: report
    - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: qoomon/deploy-to-github-pages-action@v1
        with:
          GITHUB_PAGES_SOURCE_DIR: report
          GITHUB_PAGES_BRANCH: gh-pages
          GITHUB_PAGES_REPLACE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
