name: Code quality control
on: 
  push:
  pull_request:
    types: [opened]

jobs:
  build:
    name: cppcheck
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cppcheck
          make install
      - name: Run cppcheck
        shell: bash
        run: |
          make cppcheck
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
