name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check_library: disable
          skip_preprocessor: disable
          enable: all
          exclude_check: ./lib
          inconclusive: enable
          inline_suppression: disable 
          force: disable
          std: c++17
          output_file: ./cppcheck_report.txt

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: '${GITHUB_REF##*/}'
