name: Code quality control

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build & Test]
    types: [completed]
    branches:
      - '**'

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install CppCheck
      run: |
        sudo -H apt-get update -y
        sudo -H apt-get install cppcheck
    - name: Run Cppcheck
      run: cppcheck --std=c++20  -I./tests -I./src --error-exitcode=1 --xml --xml-version=2 --force --enable=all src 2>cppcheck_res.xml
    - name: Generate Report
      if: ${{ failure() }}
      run: cppcheck-htmlreport --title=WebFrame --file=cppcheck_res.xml --report-dir=report
    - name: Upload Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: report
    - name: Renaming
      if: ${{ failure() }}
      shell: bash
      run: |
        mv -f report report1
        mkdir -p gh-pages
        mv -f report1 gh-pages/codeql_report
    - name: Commit
      if: ${{ failure() }}
      shell: bash
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add gh-pages
        git commit -m "Cppcheck report" -a
    - name: Push cppcheck results
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

