name: Doxygen
on:
  workflow_run:
    workflows: [Build & Test]
    types: [completed]
    branches: [master]

jobs:
  build:
    name: doxygen
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: langroodi/doxygenize@v1.6
        with:
            doxygenconf: './Doxyfile'
            htmloutput: './documentation/html'
            ghpagesbranch: 'gh-pages'
            ghpagesdir: './docs'
            darkmode: 'true'