name: Doxygen
on:     
  push:
    branches:
      - master
      - v2

jobs:
  build:
    name: doxygen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: langroodi/doxygenize@v1.6
        with:
            doxygenconf: './Doxyfile'
            htmloutput: './documentation'
            ghpagesbranch: 'gh-pages'
            ghpagesdir: '.'
            darkmode: 'true'