name: Doxygen
on:     
  push:
    branches:
      - master
      - v2

jobs:
  build:
    name: cppcheck
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: langroodi/doxygenize@v1.6
        with:
            doxygenconf: './Doxyfile'
            htmloutput: './doc'
            ghpagesbranch: 'gh-pages'
            ghpagesdir: '.'
            darkmode: 'true'