name: Build under Ubuntu Linux

on:
  push:
  pull_request:
    types: [opened]

jobs:
  build-on-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: jinja
        run: make install
        shell: bash
      - name: root dir
        run: cd ../../../
        shell: bash
      - name: make build
        run: make build
        shell: bash
      - name: make build_test
        run: make build_test
        shell: bash
      - name: full build+run
        run: make build build_test clean run_tests
        shell: bash
