name: Build under Windows

on:
  push:
  pull_request:
    types: [opened]

jobs:
  build-on-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: jinja
        run: make install
        shell: bash
      - name: make build
        run: make build
        shell: bash
      - name: make build_test
        run: make build_test
        shell: bash
      - name: make clean
        run: make clean
        shell: bash
      - name: full build+run
        run: make build build_test clean run_tests
        shell: bash
